name: Node.js CI

on:
  push:
    branches-ignore: ""
  pull_request:
    branches-ignore: ""

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - run: echo "🔎 Running CI FOR branch ${{ github.ref }} on repository ${{ github.repository }}."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - run: npm run build --if-present
